# Generated by Django 3.1.5 on 2021-01-19 10:26

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('visible', models.BooleanField(default=True)),
                ('important', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'वर्ग',
                'verbose_name_plural': 'वर्ग',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='शीर्षक')),
                ('paragraph', models.TextField(verbose_name='विवरण')),
                ('youtube_link', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(blank=True), size=None)),
                ('publish', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='newsapp.Category', verbose_name='वर्ग')),
            ],
            options={
                'verbose_name': 'समाचार',
                'verbose_name_plural': 'समाचार',
            },
        ),
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('newsArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.newsarticle')),
            ],
            options={
                'verbose_name': 'समाचार तस्वीर',
                'verbose_name_plural': 'समाचार तस्वीर',
            },
        ),
    ]
