# Generated by Django 3.1.5 on 2021-01-14 07:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), size=None)),
            ],
        ),
    ]
