# Generated by Django 3.1.5 on 2021-01-14 14:22

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='paragraph',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=400), size=None),
        ),
    ]
