# Generated by Django 3.1.5 on 2021-01-17 11:37

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='paragraph',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), size=None, verbose_name='विवरण'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
