# Generated by Django 3.1.5 on 2021-02-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20210120_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesmodel',
            name='newsArticle',
        ),
    ]
