# Generated by Django 3.1.5 on 2021-01-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20210114_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.ManyToManyField(to='newsapp.Category'),
        ),
    ]
