# Generated by Django 3.1.5 on 2021-02-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_remove_imagesmodel_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='images',
            field=models.ManyToManyField(to='newsapp.ImagesModel'),
        ),
    ]
