# Generated by Django 3.1.5 on 2021-01-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_newsarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='images',
            field=models.ImageField(blank=True, height_field='100px', null=True, upload_to='images', width_field='100px'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
