# Generated by Django 3.1.5 on 2021-01-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20210114_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
