# Generated by Django 3.1.5 on 2021-01-14 17:44

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_newsarticle_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'वर्ग', 'verbose_name_plural': 'वर्ग'},
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'समाचार', 'verbose_name_plural': 'समाचार'},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='url_height',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='url_width',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.ManyToManyField(to='newsapp.Category', verbose_name='वर्ग'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='images',
            field=models.ImageField(blank=True, height_field='url_height', null=True, upload_to='images', width_field='url_width'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='paragraph',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=400), size=None, verbose_name='विवरण'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=200, verbose_name='शीर्षक'),
        ),
    ]
