# Generated by Django 3.1.5 on 2021-01-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20210114_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='url_width',
        ),
    ]
