# Generated by Django 3.1.5 on 2021-02-13 04:11

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_videonews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='शीर्षक')),
                ('paragraph', models.TextField(verbose_name='विवरण')),
                ('youtube_link', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(blank=True), blank=True, null=True, size=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
