# Generated by Django 3.1.5 on 2021-02-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_advertisment'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='key_words',
            field=models.ManyToManyField(to='newsapp.keyWord'),
        ),
    ]
