# Generated by Django 3.1.5 on 2021-02-13 12:42

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_auto_20210213_0417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisment',
            options={'verbose_name': 'विज्ञापन', 'verbose_name_plural': 'विज्ञापन'},
        ),
        migrations.AlterModelOptions(
            name='marque',
            options={'verbose_name': 'Ticker', 'verbose_name_plural': 'Tickers'},
        ),
        migrations.AlterModelOptions(
            name='videonews',
            options={'verbose_name': 'वीडियो समाचार', 'verbose_name_plural': 'वीडियो समाचार'},
        ),
        migrations.AddField(
            model_name='advertisment',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='marque',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='videonews',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='youtube_link',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
