# Generated by Django 3.1.5 on 2021-02-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_auto_20210213_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=200)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='imagesmodel',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='key_words',
            field=models.ManyToManyField(blank=True, to='newsapp.keyWord'),
        ),
    ]
