# Generated by Django 3.1.5 on 2021-03-06 13:10

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_auto_20210215_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='youtube_link',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
    ]
